// <copyright file="ItemGroupDefinition.Generated.cs" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

//------------------------------------------------------------------------------
// <auto-generated>
//     This source code was auto-generated by a roslyn code generator.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All

namespace MUnique.OpenMU.Persistence.BasicModel;

using MUnique.OpenMU.Persistence.Json;

/// <summary>
/// A plain implementation of <see cref="ItemGroupDefinition"/>.
/// </summary>
public partial class ItemGroupDefinition : MUnique.OpenMU.DataModel.Configuration.Items.ItemGroupDefinition, IIdentifiable, IConvertibleTo<ItemGroupDefinition>
{
    
    
    
    /// <summary>
    /// Gets the raw object of <see cref="GameConfiguration" />.
    /// </summary>
    [System.Text.Json.Serialization.JsonPropertyName("gameConfiguration")]
    public GameConfiguration RawGameConfiguration
    {
        get => base.GameConfiguration as GameConfiguration;
        set => base.GameConfiguration = value;
    }

    /// <inheritdoc/>
    [System.Text.Json.Serialization.JsonIgnore]
    public override MUnique.OpenMU.DataModel.Configuration.GameConfiguration GameConfiguration
    {
        get => base.GameConfiguration;
        set => base.GameConfiguration = value;
    }

    /// <inheritdoc />
    public override MUnique.OpenMU.DataModel.Configuration.Items.ItemGroupDefinition Clone(MUnique.OpenMU.DataModel.Configuration.GameConfiguration gameConfiguration)
    {
        var clone = new ItemGroupDefinition();
        clone.AssignValuesOf(this, gameConfiguration);
        return clone;
    }
    
    /// <inheritdoc />
    public override void AssignValuesOf(MUnique.OpenMU.DataModel.Configuration.Items.ItemGroupDefinition other, MUnique.OpenMU.DataModel.Configuration.GameConfiguration gameConfiguration)
    {
        base.AssignValuesOf(other, gameConfiguration);
        this.Id = other.GetId();
    }

    /// <inheritdoc/>
    public override bool Equals(object obj)
    {
        var baseObject = obj as IIdentifiable;
        if (baseObject != null)
        {
            return baseObject.Id == this.Id;
        }

        return base.Equals(obj);
    }

    /// <inheritdoc/>
    public override int GetHashCode()
    {
        return this.Id.GetHashCode();
    }

    /// <inheritdoc/>
    public ItemGroupDefinition Convert() => this;
}
